Lab 3 Ruby On Rails System/blog/config/routes.rb
Rails.application.routes.draw do
  get 'registration', to: 'auth#signup_form' , as: :registeration
  post 'signup' , to: 'auth#signup' ,as: 'signup'
  get 'login', to: 'auth#signin_form' , as: 'login'
  post 'signin' , to: 'auth#signin' , as: :signin
  post 'logout' , to: 'auth#logout' , as: :logout
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

    # Defines the root path route ("/")
     root "posts#index" 
end

Lab 3 Ruby On Rails System/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Lab 3 Ruby On Rails System/blog/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

Lab 3 Ruby On Rails System/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

    def authenticated_user
        return redirect_to root_path if session[:user]
    end
    def unauthenticated_user
        return redirect_to login_path unless session[:user]
    end
end

Lab 3 Ruby On Rails System/blog/app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :authenticated_user, except: [:logout]

  def signup_form 
  end

  def signup
    user = User.new(params.permit(
      :name, 
      :email,
      :password
    ))
    if user.save
      session[:user] = user
      redirect_to root_path
    else
      redirect_to register_path
    end
  end

  def signin_form
 
  end

  def signin
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user] = user
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def logout
    session[:user] = nil
    redirect_to login_path
  end
end

Lab 3 Ruby On Rails System/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :unauthenticated_user 
    def index
    end
end

Lab 3 Ruby On Rails System/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Lab 3 Ruby On Rails System/blog/app/helpers/auth_helper.rb
module AuthHelper
end

Lab 3 Ruby On Rails System/blog/app/helpers/users_helper.rb
module UsersHelper
end

Lab 3 Ruby On Rails System/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% unless session[:user]%>
        <li class="nav-item">
          <%= link_to 'Register',registeration_path , class:"nav-link"%>
        </li>
    
        <li class="nav-item">
          <%= link_to 'Login',login_path , class:"nav-link"%>
        </li>
     <% end %>
     <% if session[:user] %>
        <li class="nav-item">
          <%= button_to 'Logout',logout_path ,method: :post, class:"nav-link"%>
        </li>
     <% end %>
 
     
    </ul>
  </div>
</nav> 
    <div class="container mt-5">
    <%= yield %>
    </div>
  </body>
</html>

Lab 3 Ruby On Rails System/blog/app/views/posts/index.html.erb
Lists of posts